-- 仅移除本迁移添加的 DB 级默认值（NOT NULL 与回填数据保留，属安全增强）
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE skills ALTER COLUMN id DROP DEFAULT;
ALTER TABLE skill_versions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE skill_files ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_skill_likes ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_skill_downloads ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_skill_copies ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ripples ALTER COLUMN id DROP DEFAULT;
ALTER TABLE guest_sessions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ripple_pushes ALTER COLUMN id DROP DEFAULT;
ALTER TABLE skill_comments ALTER COLUMN id DROP DEFAULT;
